apiVersion: v1
kind: Service

metadata:
  name: url-shortener-service
  namespace: url-shortener

spec:
  selector:
    app: url-shortener-api

  ports:
    - port: 8081
      targetPort: 8081

  type: NodePort