apiVersion: v1
kind: ConfigMap

metadata:
  name: url-shortener-config
  namespace: url-shortener

data:
  PORT: "8081"

  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: urlshortener

  REDIS_HOST: redis-service
  REDIS_PORT: "6379"